spring.application.name=LinkSphere-Backend
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=${DATABASE_DRIVER}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.refresh.expiration=2592000000

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG

frontend.url=${FRONTEND_URL}
groq.api.url=${GROQ_URL}
groq.api.key=${GROQ_API_KEY}
groq.model=${GROQ_MODEL}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true