spring.application.name=LinkSphere-Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/LinkSphereDB
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver