spring.application.name=LinkSphere-Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/LinkSphereDB
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=03ab9f0c01c7650450d991d85ae2399464d1633d96a880b8fd4f4c5f82038e3e
jwt.expiration=172800000